use std::fs;
use std::path::Path;

/// Detect the project stack from marker files in the project root.
pub fn detect_stack(project_root: &Path) -> Option<String> {
    // Order matters: more specific checks first

    // Rust
    if project_root.join("Cargo.toml").exists() {
        return Some("rust".into());
    }

    // Go
    if project_root.join("go.mod").exists() {
        return Some("go".into());
    }

    // Rails (Gemfile + routes)
    if project_root.join("Gemfile").exists()
        && project_root.join("config/routes.rb").exists()
    {
        return Some("rails".into());
    }

    // Django (manage.py)
    if project_root.join("manage.py").exists() {
        return Some("django".into());
    }

    // Python (no Django)
    if project_root.join("pyproject.toml").exists()
        || project_root.join("requirements.txt").exists()
    {
        return Some("python".into());
    }

    // Ruby (no Rails)
    if project_root.join("Gemfile").exists() {
        return Some("ruby".into());
    }

    // Node.js — check package.json deps for framework detection
    if project_root.join("package.json").exists() {
        return Some(detect_node_framework(project_root));
    }

    // Docker Compose (generic)
    if has_compose_file(project_root) {
        return Some("docker-compose".into());
    }

    None
}

/// Check Node.js package.json for framework-specific dependencies.
fn detect_node_framework(project_root: &Path) -> String {
    // Check for framework config files first (faster than parsing JSON)
    if project_root.join("next.config.js").exists()
        || project_root.join("next.config.mjs").exists()
        || project_root.join("next.config.ts").exists()
    {
        return "nextjs".into();
    }

    if project_root.join("nuxt.config.js").exists()
        || project_root.join("nuxt.config.ts").exists()
    {
        return "nuxt".into();
    }

    // Fall back to parsing package.json dependencies
    let pkg_path = project_root.join("package.json");
    if let Ok(content) = fs::read_to_string(&pkg_path) {
        if let Ok(pkg) = serde_json::from_str::<serde_json::Value>(&content) {
            let has_dep = |name: &str| -> bool {
                pkg.get("dependencies")
                    .and_then(|d| d.get(name))
                    .is_some()
                    || pkg.get("devDependencies")
                        .and_then(|d| d.get(name))
                        .is_some()
            };

            if has_dep("next") {
                return "nextjs".into();
            }
            if has_dep("nuxt") {
                return "nuxt".into();
            }
        }
    }

    "node".into()
}

fn has_compose_file(project_root: &Path) -> bool {
    project_root.join("docker-compose.yml").exists()
        || project_root.join("docker-compose.yaml").exists()
        || project_root.join("compose.yml").exists()
        || project_root.join("compose.yaml").exists()
}

/// Pick the right config filename for the project. Returns
/// `wt.config.cjs` when `package.json` has `"type": "module"`
/// (otherwise Node parses `.js` as ESM and silently drops
/// `module.exports`). Falls back to `wt.config.js`.
pub fn config_filename(project_root: &Path) -> &'static str {
    let pkg_path = project_root.join("package.json");
    if let Ok(content) = fs::read_to_string(&pkg_path) {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&content) {
            if v.get("type").and_then(|t| t.as_str()) == Some("module") {
                return "wt.config.cjs";
            }
        }
    }
    "wt.config.js"
}

/// Generate a wt config file content from wizard answers. The
/// `filename` parameter is used only for the header comment; the actual
/// path is decided by the caller via `config_filename`.
pub fn generate_config(name: &str, stack: &str, worktrees_dir: &str, filename: &str) -> String {
    let mut lines = Vec::new();

    lines.push(format!("// {} — Generated by wt init", filename));
    lines.push(format!("module.exports = {{"));
    lines.push(format!("  name: '{}',", name));
    lines.push(format!("  stack: '{}',", stack));
    lines.push(String::new());
    lines.push(format!("  repo: {{"));
    lines.push(format!("    worktreesDir: '{}',", worktrees_dir));
    lines.push(format!("  }},"));
    lines.push(String::new());

    // Add lifecycle overrides section (commented out as hints)
    lines.push(format!("  // dash: {{"));
    lines.push(format!("  //   lifecycle: {{"));
    lines.push(format!("  //     local: {{"));
    lines.push(format!("  //       start: '{}',", stack_start_hint(stack)));
    lines.push(format!("  //     }},"));
    lines.push(format!("  //   }},"));
    lines.push(format!("  // }},"));

    lines.push(format!("}};"));
    lines.push(String::new());

    lines.join("\n")
}

fn stack_start_hint(stack: &str) -> &str {
    match stack {
        "node" => "npm start",
        "nextjs" => "npx next dev",
        "nuxt" => "npx nuxt dev",
        "python" | "flask" => "flask run",
        "django" => "python manage.py runserver",
        "rails" => "rails server",
        "rust" => "cargo run",
        "go" => "go run .",
        "docker-compose" => "docker compose up -d",
        _ => "npm start",
    }
}
